export type PublicDataCadence = 'live' | 'historic' | 'both';
export type PublicDataDomain = 'l1' | 'near-earth';
export type PublicDataOrbit = 'L1' | 'LEO' | 'MEO' | 'GEO' | 'HEO';
export type PublicDataReadiness = 'connected' | 'candidate' | 'archive' | 'gap';

export interface PublicSpaceWeatherSource {
  id: string;
  name: string;
  provider: string;
  domain: PublicDataDomain;
  orbit: PublicDataOrbit;
  cadence: PublicDataCadence;
  readiness: PublicDataReadiness;
  access: string;
  endpoint: string;
  variables: string[];
  spacecraft: string[];
  useCase: string;
  notes: string;
  url: string;
}

export const PUBLIC_SPACE_WEATHER_SOURCES: PublicSpaceWeatherSource[] = [
  {
    id: 'swpc-rtsw-l1',
    name: 'RTSW solar wind',
    provider: 'NOAA SWPC',
    domain: 'l1',
    orbit: 'L1',
    cadence: 'live',
    readiness: 'connected',
    access: 'JSON, no key',
    endpoint: 'services.swpc.noaa.gov/products/solar-wind/*-2-hour.json',
    variables: ['Bt', 'Bx/By/Bz GSM', 'density', 'speed', 'temperature', 'GSE position'],
    spacecraft: ['DSCOVR', 'ACE fallback'],
    useCase: 'Current upstream boundary condition and L1-to-Earth propagation input.',
    notes: 'Operational feed currently used by the live playground plots.',
    url: 'https://services.swpc.noaa.gov/products/solar-wind/',
  },
  {
    id: 'ncei-dscovr-archive',
    name: 'DSCOVR archive',
    provider: 'NOAA NCEI',
    domain: 'l1',
    orbit: 'L1',
    cadence: 'historic',
    readiness: 'candidate',
    access: 'Archive files, no key',
    endpoint: 'NCEI DSCOVR L1 data products',
    variables: ['magnetic field', 'plasma', 'ephemeris'],
    spacecraft: ['DSCOVR'],
    useCase: 'Backfill and validation for the same source family as RTSW.',
    notes: 'Use for science-quality historical windows instead of the 2-hour SWPC stream.',
    url: 'https://www.ncei.noaa.gov/products/deep-space-climate-observatory-dscovr',
  },
  {
    id: 'cdaweb-ace-wind-imap',
    name: 'ACE / WIND / IMAP HAPI',
    provider: 'NASA CDAWeb',
    domain: 'l1',
    orbit: 'L1',
    cadence: 'both',
    readiness: 'connected',
    access: 'HAPI JSON, no key',
    endpoint: 'cdaweb.gsfc.nasa.gov/hapi',
    variables: ['magnetic field', 'solar-wind plasma', 'spacecraft position'],
    spacecraft: ['ACE', 'WIND', 'IMAP'],
    useCase: 'Mission-specific L1 series, including stale-but-valid latest catalog windows.',
    notes: 'Catalog stopDate must be shown; it can lag real time by days.',
    url: 'https://cdaweb.gsfc.nasa.gov/hapi',
  },
  {
    id: 'omni-hro',
    name: 'OMNI high-resolution solar wind',
    provider: 'NASA SPDF',
    domain: 'l1',
    orbit: 'L1',
    cadence: 'historic',
    readiness: 'candidate',
    access: 'OMNIWeb / files, no key',
    endpoint: 'OMNI HRO 1-min and 5-min data',
    variables: ['bow-shock-shifted IMF', 'plasma', 'geomagnetic indices'],
    spacecraft: ['IMP 8', 'Geotail', 'WIND', 'ACE'],
    useCase: 'Model validation using time-shifted upstream solar-wind inputs.',
    notes: 'Best historical baseline for event studies at Earth response time.',
    url: 'https://omniweb.gsfc.nasa.gov/html/ow_data.html',
  },
  {
    id: 'swpc-goes-json',
    name: 'GOES primary/secondary JSON',
    provider: 'NOAA SWPC',
    domain: 'near-earth',
    orbit: 'GEO',
    cadence: 'live',
    readiness: 'connected',
    access: 'JSON, no key',
    endpoint: 'services.swpc.noaa.gov/json/goes/{primary,secondary}/*.json',
    variables: ['MAG Hp/He/Hn', 'electron flux', 'proton flux', 'XRS', 'EUVS'],
    spacecraft: ['GOES-18', 'GOES-19', 'primary', 'secondary'],
    useCase: 'Live geosynchronous environment under the magnetosphere.',
    notes: 'Plot-ready in the Admin Playground for MAG, integral particles, and XRS.',
    url: 'https://services.swpc.noaa.gov/json/goes/primary/',
  },
  {
    id: 'ncei-goes-r-mag-seiss',
    name: 'GOES-R MAG + SEISS archive',
    provider: 'NOAA NCEI',
    domain: 'near-earth',
    orbit: 'GEO',
    cadence: 'historic',
    readiness: 'connected',
    access: 'Archive files, no key',
    endpoint: 'data.ngdc.noaa.gov/platforms/solar-space-observing-satellites/goes/goes{16..19}/l2/data/{magn,mpsh,sgps}-l2-avg1m/{year}/{month}',
    variables: [
      'goes_mag_hn',
      'goes_mag_hp',
      'goes_mag_he',
      'goes_mag_h_magnitude',
      'goes_electrons_2mev',
      'goes_electrons_800kev',
      'goes_protons_10mev',
      'goes_protons_50mev',
      'goes_protons_100mev',
    ],
    spacecraft: ['GOES-16', 'GOES-17', 'GOES-18', 'GOES-19'],
    useCase: 'Primary historical GEO target source for GOES MAG |H| plus SEISS particle response.',
    notes: 'Crawler-backed NetCDF archive connector writes monthly Parquet partitions with upstream quality flags.',
    url: 'https://www.ncei.noaa.gov/products/goes-r-space-environment-in-situ',
  },
  {
    id: 'ncei-goes-sem',
    name: 'GOES 1-15 SEM archive',
    provider: 'NOAA NCEI',
    domain: 'near-earth',
    orbit: 'GEO',
    cadence: 'historic',
    readiness: 'archive',
    access: 'Archive files, no key',
    endpoint: 'GOES Space Environment Monitor archive',
    variables: ['magnetic field', 'energetic particles', 'soft X-ray'],
    spacecraft: ['SMS', 'GOES-1..15'],
    useCase: 'Long-baseline GEO climatology and storm-event model validation.',
    notes: 'Continuous geosynchronous environment record starts in 1974.',
    url: 'https://www.ngdc.noaa.gov/stp/GOES/',
  },
  {
    id: 'poes-metop-sem',
    name: 'POES / MetOp SEM',
    provider: 'NOAA NCEI',
    domain: 'near-earth',
    orbit: 'LEO',
    cadence: 'historic',
    readiness: 'candidate',
    access: 'Archive files, no key',
    endpoint: 'POES/MetOp Space Environment Monitor',
    variables: ['MEPED protons/electrons', 'TED auroral particles'],
    spacecraft: ['TIROS-N', 'NOAA POES', 'MetOp'],
    useCase: 'LEO radiation-belt precipitation and polar-orbit dose validation.',
    notes: 'Daily archive files cover polar-orbit particle environments.',
    url: 'https://www.ncei.noaa.gov/products/poes-metop-space-environment-monitor',
  },
  {
    id: 'us-tec-gnss',
    name: 'US-TEC GNSS ionosphere',
    provider: 'NOAA SWPC / NCEI',
    domain: 'near-earth',
    orbit: 'MEO',
    cadence: 'both',
    readiness: 'candidate',
    access: 'SWPC/NCEI files, no key',
    endpoint: 'US-TEC vertical and slant TEC products',
    variables: ['vertical TEC', 'slant TEC', 'uncertainty', '10-day trend'],
    spacecraft: ['GNSS', 'GPS', 'MEO'],
    useCase: 'Near-real-time and archive ionospheric response from GNSS receiver assimilation.',
    notes: 'Not spacecraft in-situ telemetry; use as Earth-near ionosphere validation data.',
    url: 'https://www.ngdc.noaa.gov/stp/IONO/ustec/',
  },
  {
    id: 'lanl-gps-energetic-particles',
    name: 'GPS energetic particles',
    provider: 'LANL / NOAA NCEI',
    domain: 'near-earth',
    orbit: 'MEO',
    cadence: 'historic',
    readiness: 'archive',
    access: 'Archive files, no key',
    endpoint: 'LANL GPS energetic particle data',
    variables: ['electron flux', 'proton flux', 'radiation-belt particles'],
    spacecraft: ['GPS', 'MEO', 'NS41'],
    useCase: 'Historical MEO radiation-belt validation from GPS constellation particle instruments.',
    notes: 'Public historical data product; use for model validation rather than live operations.',
    url: 'https://www.ncei.noaa.gov/products/space-weather/partners/lanl-products-data',
  },
  {
    id: 'dmsp-space-weather',
    name: 'DMSP space weather',
    provider: 'NOAA NCEI / NASA CDAWeb',
    domain: 'near-earth',
    orbit: 'LEO',
    cadence: 'historic',
    readiness: 'candidate',
    access: 'Archive files and CDAWeb, no key',
    endpoint: 'DMSP SSJ / SSIES / SSM',
    variables: ['precipitating particles', 'ion/electron plasma', 'magnetic field'],
    spacecraft: ['DMSP F06-F20'],
    useCase: 'LEO ionosphere, auroral precipitation, plasma drift, and magnetic perturbations.',
    notes: 'Good LEO companion to POES when validating Earth-proximal response.',
    url: 'https://www.ngdc.noaa.gov/stp/satellite/dmsp/',
  },
  {
    id: 'starlink-ephemerides',
    name: 'Starlink ephemerides',
    provider: 'SpaceX / Space-Track',
    domain: 'near-earth',
    orbit: 'LEO',
    cadence: 'both',
    readiness: 'candidate',
    access: 'Space-Track account / public files',
    endpoint: 'space-track.org publicFiles / Starlink Modified ITC ephemerides',
    variables: ['position', 'velocity', 'covariance', 'drag proxy', 'maneuver proxy'],
    spacecraft: ['Starlink', 'SpaceX', 'LEO'],
    useCase: 'LEO thermospheric density and drag proxy from Starlink orbit changes.',
    notes: 'Not direct plasma or particle telemetry; derive density proxies from ephemeris updates.',
    url: 'https://www.starlink.com/satellite-operators',
  },
  {
    id: 'space-track-tle-history',
    name: 'Space-Track TLE history',
    provider: 'Space-Track / public mirrors',
    domain: 'near-earth',
    orbit: 'LEO',
    cadence: 'historic',
    readiness: 'archive',
    access: 'Bulk TLE archive / derived mirrors',
    endpoint: 'Space-Track yearly bulk exports and Starlink TLE mirrors',
    variables: ['TLE', 'B* drag term', 'mean motion', 'altitude decay'],
    spacecraft: ['Starlink', 'OneWeb', 'active', 'LEO'],
    useCase: 'Historical orbital-drag proxy for LEO density and constellation response studies.',
    notes: 'Lower fidelity than precise Starlink ephemerides, but easier to archive over long spans.',
    url: 'https://huggingface.co/datasets/oxzoid/space-track-tle-history',
  },
  {
    id: 'cdaweb-mms-themis-rbsp',
    name: 'MMS / THEMIS / Van Allen Probes',
    provider: 'NASA CDAWeb',
    domain: 'near-earth',
    orbit: 'HEO',
    cadence: 'historic',
    readiness: 'candidate',
    access: 'HAPI/CDF, no key',
    endpoint: 'CDAWeb mission datasets',
    variables: ['fields', 'plasma', 'energetic particles', 'ephemeris'],
    spacecraft: ['MMS', 'THEMIS', 'RBSP-A', 'RBSP-B'],
    useCase: 'Magnetosphere and radiation-belt validation beyond simple LEO/GEO bins.',
    notes: 'Use as MEO/HEO bridge until a public operational MEO feed is identified.',
    url: 'https://cdaweb.gsfc.nasa.gov/hapi',
  },
  {
    id: 'celestrak-gp',
    name: 'CelesTrak GP orbit catalog',
    provider: 'CelesTrak',
    domain: 'near-earth',
    orbit: 'LEO',
    cadence: 'live',
    readiness: 'candidate',
    access: 'TLE/OMM JSON/CSV, no key',
    endpoint: 'celestrak.org/NORAD/elements/gp.php',
    variables: ['TLE', 'OMM', 'orbital elements'],
    spacecraft: ['active', 'stations', 'weather', 'GNSS', 'GEO'],
    useCase: 'Orbit-region assignment and satellite selection context for LEO/MEO/GEO.',
    notes: 'Not an in-situ environment feed; pair with space-weather data by orbit and time.',
    url: 'https://www.celestrak.org/NORAD/documentation/gp-data-formats.php',
  },
  {
    id: 'meo-public-gap',
    name: 'Operational MEO in-situ gap',
    provider: 'TBD',
    domain: 'near-earth',
    orbit: 'MEO',
    cadence: 'historic',
    readiness: 'gap',
    access: 'No robust no-key public live feed confirmed',
    endpoint: 'Pending source confirmation',
    variables: ['outer-belt electrons', 'protons', 'dose proxies'],
    spacecraft: ['GNSS/MEO candidates'],
    useCase: 'Track the missing MEO layer explicitly instead of silently faking coverage.',
    notes: 'Use RBSP/MMS/THEMIS and GEO/LEO bracketing until a public MEO feed is confirmed.',
    url: 'https://www.spaceweather.gov/phenomena/radiation-belts',
  },
];

export const L1_PUBLIC_SOURCES = PUBLIC_SPACE_WEATHER_SOURCES.filter(
  source => source.domain === 'l1',
);

export const NEAR_EARTH_PUBLIC_SOURCES = PUBLIC_SPACE_WEATHER_SOURCES.filter(
  source => source.domain === 'near-earth',
);
